### ISSUE TITLE
RuntimeError: The size of tensor a (1687) must match the size of tensor b (1688) at non-singleton dimension 2

### ISSUE THREAD

**Issue by KevinWang676** [daswer123/xtts-finetune-tests#2]
Hi, thanks for sharing the fine-tuning code! When I run the training code `!python train_dvae.py --dataset_path processed_dataset --language zh`, I got the following error. Could you help me resolve the issue? Thanks!

```
dvae.pth already exists. Skipping download.
mel_stats.pth already exists. Skipping download.
Computing mel-spectrograms: 100% 155/155 [00:02<00:00, 56.19it/s]
Computing mel-spectrograms: 100% 39/39 [00:00<00:00, 53.21it/s]
 > Filtering invalid eval samples!!
 > Total eval samples after filtering: 39
 > Sampling by language: dict_keys(['zh'])
Epoch 1/20:   0% 0/16 [00:00<?, ?it/s]/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
Epoch 1/20:   6% 1/16 [00:01<00:21,  1.46s/it, commit_loss=0.238, global_step=1, loss=0.35, recon_loss=0.112, step=1/16]/usr/local/lib/python3.10/dist-packages/TTS/tts/layers/xtts/dvae.py:381: UserWarning: Using a target size (torch.Size([10, 80, 1688])) that is different to the input size (torch.Size([10, 80, 1687])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  recon_loss = self.loss_fn(img, out, reduction="none")
Epoch 1/20:   6% 1/16 [00:01<00:22,  1.51s/it, commit_loss=0.238, global_step=1, loss=0.35, recon_loss=0.112, step=1/16]
Traceback (most recent call last):
  File "/content/xtts-finetune-tests/dvae-finetune/train_dvae.py", line 272, in <module>
    train_dvae(args)
  File "/content/xtts-finetune-tests/dvae-finetune/train_dvae.py", line 160, in train_dvae
    recon_loss, commitment_loss, out = dvae(batch['mel'].cuda())
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/TTS/tts/layers/xtts/dvae.py", line 381, in forward
    recon_loss = self.loss_fn(img, out, reduction="none")
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 3365, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/usr/local/lib/python3.10/dist-packages/torch/functional.py", line 76, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
RuntimeError: The size of tensor a (1687) must match the size of tensor b (1688) at non-singleton dimension 2
```

**Comment by KevinWang676** [comment]
@daswer123 Could you take a look at this issue? I kept getting the same RuntimeError. Thanks!

**Comment by saiful9379** [comment]
@daswer123 thank for sharing the dvae fine-tune code, i have the same issue like @KevinWang676 , it will be more convenient if you give feedback about the issue,

`Epoch 1/20:   0%|         | 1/656 [00:00<08:48,  1.24it/s, commit_loss=0.235, global_step=2, loss=0.333, recon_loss=0.0978, step=2/656]/media/sayan/hdd1/TTS/BanglaXTTS-dev-saiful/dvae_training/dvae-finetune/module/dvae.py:378: UserWarning: Using a target size (torch.Size([10, 80, 768])) that is different to the input size (torch.Size([10, 80, 767])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.`

**Comment by Fariq-22** [comment]
check it out
https://github.com/anhnh2002/XTTSv2-Finetuning-for-New-Languages

**Comment by Alyxhelpme** [comment]
Hiya! I looked into these issues and I'm still new to TTS processing so I don't know the reason why this is happening (might be the resampling of the training audios didn't look into it that much)... but I came up with a fix (if you forcibly want to use this training script).

The tensor vector must be the same size for the input and output images so I tweaked the script to pad the audio sources.
This needs to be done in the dvae.py file from the TTS library:  e.g. **\3.11.0\lib\python3.11\site-packages\TTS\tts\layers\xtts\dvae.py**



        # Find the maximum sequence length
        max_len = max(img.shape[-1], out.shape[-1])

        # Pad the shorter tensor
        img = F.pad(img, (0, max_len - img.shape[-1]))  # Pad to the right
        out = F.pad(out, (0, max_len - out.shape[-1]))  # Pad to the right

        # Create a mask (1 for real data, 0 for padding)
        mask = torch.ones_like(img)
        mask[:, :, img.shape[-1]:] = 0  # Mark padding as 0s

This part must be added before the reconstruction of loss line `recon_loss = self.loss_fn(img, out, [reduction="none")`


After this I encountered an issue when training the GPT model, and that it was loading the entire model, when in training it only needed the state dictionary. What I did was only extract the state dict from the model before setting it in the GPTArgs configuration:



    import torch
    
    # # Load the state_dict from the checkpoint file
    dvae_model = torch.load(DVAE_CHECKPOINT, map_location="cpu", weights_only=True)
    
    # Extract the state_dict
    state_dict = dvae_model.state_dict()
    
    DVAE_CHECKPOINT = f"dvae-train/finetuned_dvae_en_epoch20_state_dict.pth"
    
    # Save only the state_dict properly
    torch.save(state_dict, f"{DVAE_CHECKPOINT}")


After the training my model performed godawfully bad, but it could be reelated to my dataset's quality, epochs or even the paddding of the DVAE model, not quite sure about that.

**Comment by JinYuanZhang999** [comment]
@Alyxhelpme Thank you for the solution you provided! After fine-tuning the GPT module, the results are still quite poor. Have you identified the specific reason?

**Comment by JinYuanZhang999** [comment]
@Alyxhelpme Thank you for the solution you provided! I fine-tuned the GPT module following your approach, but the generated audio quality is still poor. Have you identified the specific reason?
